import assert from 'node:assert/strict';
import fs from 'node:fs';
import {features,predict,analyze,frequencyMap} from '../dist/dsp.mjs';
import {inspectFile,readPCM} from '../dist/input.mjs';
const root=new URL('../',import.meta.url),read=p=>JSON.parse(fs.readFileSync(new URL(p,root))),m=read('model-baseline.json'),fixture=read('tests/parity.json');
let tests=0;const test=(name,fn)=>{fn();tests++;console.log('PASS',name);};
test('Python to JavaScript feature parity',()=>{const f=features(fixture.wave);const error=Math.max(...f.map((v,i)=>Math.abs(v-fixture.features[i])));assert(error<1e-8,'Feature drift '+error);});
test('Exported SVM probability parity',()=>assert(Math.abs(predict(fixture.wave,m).probability-fixture.probability)<1e-8));
test('Silence rejected',()=>assert.throws(()=>analyze(new Float32Array(48000),m),/No usable/));
test('Short input rejected',()=>assert.throws(()=>analyze(new Float32Array(16000),m),/at least 2/));
test('Long input rejected',()=>assert.throws(()=>analyze(new Float32Array(976000),m),/60/));
test('NaN rejected',()=>assert.throws(()=>analyze(Float32Array.from({length:48000},()=>NaN),m),/invalid/));
test('Malformed header rejected',()=>assert.throws(()=>inspectFile(new ArrayBuffer(100))));
test('Oversized file rejected',()=>assert.throws(()=>inspectFile(new ArrayBuffer(20*1024*1024+1)),/20 MB/));
const b=fs.readFileSync(new URL('dist/audio/clip-01.wav',root));const ab=b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);const info=inspectFile(ab);
test('Real WAV parsing and duration',()=>{assert.equal(info.rate,16000);assert.equal(info.channels,1);assert(info.duration>=2);});
test('Truncated WAV rejected',()=>assert.throws(()=>inspectFile(ab.slice(0,ab.byteLength-32)),/truncated/));
test('Repeat runs are identical',()=>{let x=readPCM(ab,info);assert.deepEqual(analyze(x,m),analyze(x,m));});
test('Frequency map is finite, bounded and uses 26 mel bands',()=>{const map=frequencyMap(readPCM(ab,info));assert.equal(map.bands,26);assert(map.columns>0&&map.columns<=72);assert(map.values.flat().every(v=>Number.isFinite(v)&&v>=0&&v<=1));});
test('MP3 inspection exposes input rate and channel count',()=>{const p=fs.readFileSync(new URL('tests/mp3-fixture.mp3',root)),pi=inspectFile(p.buffer.slice(p.byteOffset,p.byteOffset+p.byteLength));assert(pi.rate>=8000);assert([1,2].includes(pi.channels));});
test('Clip quality forces uncertainty',()=>{let x=Float32Array.from({length:48000},(_,i)=>i%2?1:-1);assert.equal(analyze(x,m).label,'uncertain');});
const source=fs.readFileSync(new URL('dist/app.mjs',root),'utf8'),html=fs.readFileSync(new URL('dist/index.html',root),'utf8');
test('All literal UI ID selectors exist',()=>{for(const match of source.matchAll(/\$\(['"]#([\w-]+)['"]\)/g))assert(html.includes('id="'+match[1]+'"'),match[1]);});
test('User-controlled content is never HTML injected',()=>{assert(!source.includes('innerHTML'));assert(!source.includes('eval('));assert(!source.includes('localStorage'));});
test('Upload decoder has size, format, duration boundaries',()=>{assert(source.includes('inspectFile(buffer)'));assert(html.includes('Content-Security-Policy'));assert(source.includes('45000'));});
fs.writeFileSync(new URL('tests/core-results.json',root),JSON.stringify({passed:tests,failed:0,featureTolerance:1e-8,probabilityTolerance:1e-8},null,2));
